---
title: "Program"
---

### Call for papers

All applicants must submit an abstract to be considered for attendance at the workshop. 

Please use this [abstract template](files/cmc-abstracts_word_template.docx).

- Abstracts are submitted during [registration](registration.qmd).

- Abstracts have a 500-word limit and should be submitted as a Word or PDF attachment during registration by __February 1, 2026__. 

- Submissions will be reviewed by the Program Committee and applicants will be notified of acceptance to the workshop by __February 15, 2026__ using the e-mail address provided in the submission form.

If a submitted abstract is accepted, one of the following will apply, depending on the results of the review:

- Accepted for _oral presentation_ at the workshop within a 20 minute time slot with extra 10 min for discussion.

- Accepted for _live demonstration_ at the workshop within a 15 minute time slot with extra 5 min for discussion.

- Accepted for _poster presentation_ (authors will present and discuss topics in one special poster session)


### Workshop topics 

Main conference topics are (but not limited to):

-   Relief representation

-   UAV and LiDAR data for terrain mapping

-   Artificial Intelligence in mountain cartography

-   Mapping for outdoor activities in mountains

-   Mapping and GIS of mountainous areas

-   Physical and topographic mapping

-   Mountain and glacier dynamics

-   Interactive atlases and new media applications

-   Other

### Presentation formats

The following presentation formats are welcomed:

- Oral presentation
- Live demonstration
- Poster presentation

### Preliminary schedule

| Day | Date | Events |
|------------------|------------------|-----------------------------------|
| 1 | April 22 | Arrival, official start in the evening with a keynote or the appropriate opening |
| 2-4 | April 23-25 | Depending on the weather, one day outdoors and two days indoors (flexible schedule) |
| 4 | April 25 | Late afternoon final workshop closing remarks. Traditional local dinner |
| 5 | April 26 | Departure in the morning |

: Preliminary workshop schedule