---
title: "Travel"
---

```{=html}
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d322570.75559295056!2d15.207671686165451!3d50.83025909383657!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x470ecf7dae8b1143%3A0x13361d4e355a1b79!2sWellness%20Hotel%20Svornost%20-%20Pool%20accees%20in%20the%20accomodation%20price!5e0!3m2!1sru!2sus!4v1763393009272!5m2!1sru!2sus" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
```

If you are going from the airport, a the most convenient way is by bus.

### By bus

You can use [IDOS](https://idos.cz/vlakyautobusymhdvse/spojeni/vysledky/?f=Letiště%20Praha&fc=200003&t=Harrachov;%20Jablonec%20nad%20Nisou&tc=1) bus operator. *We recommend buying tickets in advance*

Way from the airport:

1.  Praha Airport - bus line 100 to metro station Zličín
2.  Use metro B, Zličín to the final stop Černý most. You need to buy a 90-minute metro ticket (the journey takes 40 minutes without transfers)
3.  There is a bus station, here you can take the long-distance bus line 700 or 900

### By train

You can use [České dráhy](https://www.cd.cz/en/default.htm) railway operator.

Way from the airport:

1.  Take the bus from the airport AE 1042 to Prague main station
2.  Take the train to Harrachov.
3.  You must change trains at least once, in Tanvald. The actual number of transfers varies depending on the individual times

::: {.callout-note}
Train service to Harrachov is infrequent and generally slow, often requiring multiple transfers, so taking a bus is the recommended option.
:::

### By Bolt taxi

For an extremely convenient—but costly—option, you can take a Bolt directly from Prague Airport to Hotel Svornost. 

- Prices start at around __3,500 CZK__ per group of up to four travelers. 
- Request the ride through the Bolt app and always check that the car has enough space for your party, including luggage.

### By car

Approximate travel duration to Harrachov by car:

-   from Prague airport \~2.5 hours (depending on rush hour, you take the D10)
-   from Dresden \~3 hours
-   from Wrocław \~2 hours

### Taxi in Harrachov

| | Name | Phone number |
|----|-----------|---------------------------------------------------------|
| 1 | ARNES TAXI | <a href="tel:+420776722131">+420 776 722 131</a> |
| 2 | TAXI TONDR | <a href="tel:+420602353578">+420 602 353 578</a> |
| 3 | TAXI KONVALINKA | <a href="tel:+420777288470">+420 777 288 470</a> |
| 4 | CENTRAL TAXI | <a href="tel:+420608400699">+420 608 400 699</a> |